AVStaffing/Controllers/PhysicianController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AVStaffing.Models.Constants;
using AVStaffing.Models.Entities;

namespace AVStaffing.Controllers
{
    public class PhysicianController : BaseController
    {

        [HttpGet]
        public ActionResult PhysicianList()
        {
            var physicianList = DbContext.Users.Where(x=>x.Roles.Any(y=>y.Role.Name == Roles.Physician)).ToList();
            return View(physicianList);
        }

     

    }
}

AVStaffing/Views/Physician/AddPhysician.cshtml
@model MyHealthCare.Infrastructure.Physician
@{
    ViewBag.Title = "AddPhysician";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .field-validation-error {
        color: red
    }

    .validation-summary-errors {
        color: red;
    }
</style>

<div class="subheader py-2 py-lg-6  subheader-transparent " id="kt_subheader">
    <div class=" container  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <div class="d-flex align-items-center flex-wrap mr-1">
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <h5 class="text-dark font-weight-bold my-1 mr-5">
                    Physician Management
                </h5>
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="#/" class="text-muted">
                            Account
                        </a>
                    </li>

                    <li class="breadcrumb-item">
                        <a href="#/" class="text-muted">
                            Add Physician
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="d-flex flex-column-fluid">
    <div class="container">
        @using (Html.BeginForm("AddPhysician", "Physician", FormMethod.Post))
        {
            @Html.HiddenFor(x => x.Id)

            <div class="card card-custom justify-content-center">
                <div class="card-header">
                    <div class="card-title">
                        <span class="card-icon"><i class="fa fa-user text-primary"></i></span>
                        <h3 class="card-label">
                            @if (Model.Id != 0)
                            {

                                @Html.Raw("Update Physician")
                            }
                            else
                            {
                                @Html.Raw("Create Physician")
                            }
                        </h3>
                    </div>
                </div>

                <div class="card-body">
                    <div class="row">

                        <div class="col-md-7 my-2">
                            <div class="form-group row">
                                @Html.ValidationSummary(true)
                            </div>

                            <div class="form-group">
                                @Html.HiddenFor(x => x.Id)
                                @Html.LabelFor(x => x.Name)
                                @Html.TextBoxFor(x => x.Name, new { @class = "form-control", placeholder = "Name" })
                                @Html.ValidationMessageFor(x => x.Name)
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(x => x.Email)
                                @Html.TextBoxFor(x => x.Email, new { @class = "form-control", placeholder = "Username" })
                                @Html.ValidationMessageFor(x => x.Email)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(x => x.PhoneNumber)
                                @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control", placeholder = "Password" })
                                @Html.ValidationMessageFor(x => x.PhoneNumber)
                            </div>


                        </div>

                        <div class="form-group">
                            <div class="float-right">
                                <a href="@Url.Action("AddPhysician", "Physician")" class="btn btn-default font-weight-bold btn-sm px-3 font-size-base">
                                    Back
                                </a>

                                <div class="btn-group ml-2">
                                    <button type="submit" class="btn btn-primary font-weight-bold btn-sm px-3 font-size-base">
                                        @if (Model.Id == 0)
                                        {
                                            @Html.Raw("Add Physician")
                                        }
                                        else
                                        {
                                            @Html.Raw("Save Changes")
                                        }
                                    </button>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts
{

    
}

AVStaffing/Views/Physician/PhysicianList.cshtml
@model IEnumerable <AVStaffing.Infrastructure.ApplicationUser>

@{
    ViewBag.Title = "Proxies";

    var editPhysicianPermission = User.HasPermission("Physician-AddPhysician");
    var deletePhysicianPermission = User.HasPermission("Physician-DeletePhysician");
}
<div class="subheader py-2 py-lg-6  subheader-transparent " id="kt_subheader">
    <div class=" container  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <div class="d-flex align-items-center flex-wrap mr-1">
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <h5 class="text-dark font-weight-bold my-1 mr-5">
                    Physician Management
                </h5>
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="#/" class="text-muted">
                            Account
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#/" class="text-muted">
                            Proxies
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="d-flex flex-column-fluid">
    <div class="container">
        <div class="card card-custom">
            <div class="card-header">
                <div class="card-title">
                    <span class="card-icon"><i class="fa fa-user text-primary"></i></span>
                    <h3 class="card-label">Physician List</h3>
                </div>
                <div class="card-toolbar">
                    @if (editPhysicianPermission)
                    {
                        <a href="@Url.Action("AddUser", "User")" class="btn btn-primary font-weight-bolder">
                            <i class="la la-plus"></i>
                            Create new Physician
                        </a>
                    }
                </div>
            </div>
            <div class="card-body">
                <table  class="table table-separate table-head-custom collapsed dataTable">
                    <thead>
                        <tr>
                            <th>Physician Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Action</th>
                        </tr>
                    <thead>

                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@item.FirstName @item.LastName</td>
                                <td>@item.Email</td>
                                <td>@item.PhoneNumber</td>>
                                <td>
                                    @if (editPhysicianPermission)
                                    {
                                        <a style="cursor: pointer !important" href="@Url.Action("AddPhysician", "Physician", new {id = item.Id})" id=@item.Id>
                                            <i class="fas fa-pencil-alt text-primary"></i>
                                        </a>
                                    }
                                    @if (deletePhysicianPermission)
                                    {
                                        <a style="cursor: pointer !important" href="#/" class="deletePhysician" data-id="@item.Id">
                                            <i class="fas fa-trash text-danger"></i>
                                        </a>
                                    }
                                </td>
                            </tr>
                            }
                        </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
     

        $(".deletePhysician").click(function() {
            var id = $(this).data("id");
            var row = $(this).parents("tr");
            bootbox.confirm("Are you sure you want to delete this user ?",
                function(r) {
                    if (r) {
                        $.post("@Url.Action("DeletePhysician", "Physician")",
                                {
                                    PhysicianId: id
                                })
                            .done(function() {
                                $(row).remove();
                            })
                            .fail(function() {

                            });
                    }
                });
        });

    </script>
}