AVStaffing/Controllers/GoalController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AVStaffing.Models.Entities;

namespace AVStaffing.Controllers
{
    public class GoalController : BaseController
    {

        [HttpGet]
        public ActionResult GoalList()
        {
            var goalList = DbContext.Goals.ToList();
            return View(goalList);
        }

        [HttpGet]
        public ActionResult AddGoal(int goalId = 0)
        {
            var goal = new Goal();
            if (goalId != 0)
            {
                goal = DbContext.Goals.FirstOrDefault(x => x.Id == goalId);
            }
            return View(goal);
        }

        [HttpPost]
        public ActionResult AddGoal(Goal goal)
        {
            DbContext.Goals.AddOrUpdate(goal);
            DbContext.SaveChanges();
            return RedirectToAction(nameof(AddGoal));
        }

        [HttpPost]
        public ActionResult DeleteGoal(int goalId)
        {
            try
            {
                var goal = DbContext.Goals.First(x => x.Id == goalId);
                DbContext.Goals.Remove(goal);
                DbContext.SaveChanges();
                return Json(true);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }
    }
}

AVStaffing/Views/Goal/AddGoal.cshtml
@model AVStaffing.Models.Entities.Goal
@{
    ViewBag.Title = "AddGoal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .field-validation-error {
        color: red
    }

    .validation-summary-errors {
        color: red;
    }
</style>

<div class="subheader py-2 py-lg-6  subheader-transparent " id="kt_subheader">
    <div class=" container  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <div class="d-flex align-items-center flex-wrap mr-1">
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <h5 class="text-dark font-weight-bold my-1 mr-5">
                    Goal Management
                </h5>
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="#/" class="text-muted">
                            Account
                        </a>
                    </li>

                    <li class="breadcrumb-item">
                        <a href="#/" class="text-muted">
                            Add Goal
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="d-flex flex-column-fluid">
    <div class="container">
        @using (Html.BeginForm("AddGoal", "Goal", FormMethod.Post))
        {
            @Html.HiddenFor(x => x.Id)

            <div class="card card-custom justify-content-center">
                <div class="card-header">
                    <div class="card-title">
                        <span class="card-icon"><i class="fa fa-user text-primary"></i></span>
                        <h3 class="card-label">
                            @if (Model.Id != 0)
                            {

                                @Html.Raw("Update Goal")
                            }
                            else
                            {
                                @Html.Raw("Create Goal")
                            }
                        </h3>
                    </div>
                </div>

                <div class="card-body">
                    <div class="row">

                        <div class="col-md-7 my-2">
                            <div class="form-group row">
                                @Html.ValidationSummary(true)
                            </div>

                            <div class="form-group">
                                @Html.HiddenFor(x => x.Id)
                                @Html.LabelFor(x => x.GoalName)
                                @Html.TextBoxFor(x => x.GoalName, new { @class = "form-control", placeholder = "Goal Name" })
                                @Html.ValidationMessageFor(x => x.GoalName)
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(x => x.GoalTitle)
                                @Html.TextBoxFor(x => x.GoalTitle, new { @class = "form-control", placeholder = "Goal Title" })
                                @Html.ValidationMessageFor(x => x.GoalTitle)
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(x => x.Description)
                                @Html.TextBoxFor(x => x.Description, new { @class = "form-control", placeholder = "Description" })
                                @Html.ValidationMessageFor(x => x.Description)
                            </div>



                        </div>

                        <div class="form-group">
                            <div class="float-right">
                                <a href="@Url.Action("AddGoal", "Goal")" class="btn btn-default font-weight-bold btn-sm px-3 font-size-base">
                                    Back
                                </a>

                                <div class="btn-group ml-2">
                                    <button type="submit" class="btn btn-primary font-weight-bold btn-sm px-3 font-size-base">
                                        @if (Model.Id == 0)
                                        {
                                            @Html.Raw("Add Goal")
                                        }
                                        else
                                        {
                                            @Html.Raw("Save Changes")
                                        }
                                    </button>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts
{
    <script src="https://cdn.tiny.cloud/1/bvop19e8cyzwod147lpbd1e77sd2gfgu7e2quc2jq80tl0lc/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>


        function initMCEexact(e, initialValue) {
            tinymce.init({
                initialValue: initialValue,
                directionality: 'ltr',
                selector: e,
                toolbar_mode: 'floating',
                height: 900,
                images_upload_url: "@Url.Action("AddMedia", "Content")",
                image_list: "@Url.Action("GetMedia", "Content")",
                paste_data_images: true,
                automatic_uploads: true,
                branding: false,
                image_advtab: true,
                images_upload_handler: function(blobInfo, success, failure, progress) {
                    var formData;
                    var xhr = new XMLHttpRequest();
                    xhr.withCredentials = false;
                    xhr.open('POST', `@Url.Action("AddMedia", "Content")`);
                    xhr.upload.onprogress = function(e) {
                        progress(e.loaded / e.total * 100);
                    };

                    xhr.onload = function() {
                        var json;

                        if (xhr.status < 200 || xhr.status >= 300) {
                            failure('HTTP Error: ' + xhr.status);
                            return;
                        }

                        json = JSON.parse(xhr.responseText);

                        if (!json || typeof json.MediaUrl != 'string') {
                            failure('Invalid JSON: ' + xhr.responseText);
                            return;
                        }
                        success(json.MediaUrl);
                    };

                    xhr.onerror = function() {
                        failure('Image upload failed due to a XHR Transport error. Code: ' + xhr.status);
                    };

                    formData = new FormData();
                    formData.append('file', blobInfo.blob(), blobInfo.filename());
                    xhr.send(formData);
                },
                plugins: [
                    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                    'searchreplace visualblocks code fullscreen',
                    'image code',
                    'image imagetools',
                    'insertdatetime media table paste code help wordcount',
                ],
                toolbar:
                    'undo redo | image code | formatselect | bold italic backcolor | \
                                                                alignleft aligncenter alignright alignjustify | \
                                                                bullist numlist outdent indent | removeformat',
                menu: {
                    file: { title: 'File', items: ' preview | print ' }
                },
                menubar: 'file edit view insert format tools table',
                apply_source_formatting: true

            });
        }


        initMCEexact("#Description", `@Html.Raw(Model.Description)`);




    </script>
}

}

AVStaffing/Views/Goal/GoalList.cshtml
@model IEnumerable<AVStaffing.Models.Entities.Goal>
@{
    ViewBag.Title = "Proxies";

    var editGoalPermission = User.HasPermission("Goal-AddGoal");
    var deleteGoalPermission = User.HasPermission("Goal-DeleteGoal");
}
<div class="subheader py-2 py-lg-6  subheader-transparent " id="kt_subheader">
    <div class=" container  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <div class="d-flex align-items-center flex-wrap mr-1">
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <h5 class="text-dark font-weight-bold my-1 mr-5">
                    Goal Management
                </h5>
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="#/" class="text-muted">
                            Document
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#/" class="text-muted">
                            Goals
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="d-flex flex-column-fluid">
    <div class="container">
        <div class="card card-custom">
            <div class="card-header">
                <div class="card-title">
                    <span class="card-icon"><i class="fa fa-user text-primary"></i></span>
                    <h3 class="card-label">Goal List</h3>
                </div>
                <div class="card-toolbar">
                    @if (editGoalPermission)
                    {
                        <a href="@Url.Action("AddGoal", "Goal")" class="btn btn-primary font-weight-bolder">
                            <i class="la la-plus"></i>
                            Create new Goal
                        </a>
                    }
                </div>
            </div>
            <div class="card-body">
                <table  class="table table-separate table-head-custom collapsed dataTable">
                    <thead>
                        <tr>
                            <th>Goal Name</th>
                            <th>Goal Title</th>
                            <th>Description</th>
                            <th>Action</th>
                        </tr>
                    <thead>

                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@item.GoalName</td>
                                <td>@item.GoalTitle</td>
                                <td>@Html.Raw(item.Description)</td>

                                <td>
                                    @if (editGoalPermission)
                                    {
                                        <a style="cursor: pointer !important" href="@Url.Action("AddGoal", "Goal", new {id = item.Id})" id=@item.Id>
                                            <i class="fas fa-pencil-alt text-primary"></i>
                                        </a>
                                    }
                                    @if (deleteGoalPermission)
                                    {
                                        <a style="cursor: pointer !important" href="#/" class="deleteGoal" data-id="@item.Id">
                                            <i class="fas fa-trash text-danger"></i>
                                        </a>
                                    }
                                </td>
                            </tr>
                            }
                        </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
     

        $(".deleteGoal").click(function() {
            var id = $(this).data("id");
            var row = $(this).parents("tr");
            bootbox.confirm("Are you sure you want to delete this user ?",
                function(r) {
                    if (r) {
                        $.post("@Url.Action("DeleteGoal", "Goal")",
                                {
                                    GoalId: id
                                })
                            .done(function() {
                                $(row).remove();
                            })
                            .fail(function() {

                            });
                    }
                });
        });

    </script>
}