AVStaffing/Controllers/NightLogController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AVStaffing.Infrastructure;
using AVStaffing.Models;
using AVStaffing.Models.Constants;
using AVStaffing.Models.Entities;
using AVStaffing.Models.ViewModels;

namespace AVStaffing.Controllers
{

    public class NightLog_VM
    {
        public List<ApplicationUser> Patients { get; set; }
        public NightLog NightLog { get; set; }
        public List<NightLogTime> NightLogTimes { get; set; }
        public List<ApplicationUser> Staff { get; set; }

        public NightLog_VM()
        {
            Patients = new List<ApplicationUser>();
            NightLog  = new NightLog();
            NightLogTimes = new List<NightLogTime>();
        }
    }


    public class NightLogController : BaseController
    {

        [HttpGet]
        public ActionResult NightLogList()
        {
            var NightLogList = DbContext.NightLogs.Include(x => x.Patient).Include(x => x.NightLogTimes).ToList();
            return View(NightLogList);
        }

        [HttpGet]
        public ActionResult AddNightLog(int id = 0)
        {
            var vm = new NightLog_VM { NightLog = new NightLog() };
            if (id != 0)
            {
                vm.NightLog = DbContext.NightLogs.Include(x => x.NightLogTimes).FirstOrDefault(x => x.Id == id);
                if (vm.NightLog == null)
                {
                    vm.NightLog = new NightLog();
                }
            }

            CreateNightLogRows(vm.NightLog);
            vm.Patients = DbContext.Users.Where(x => x.Roles.Any(y => y.Role.Name == Roles.Patient)).ToList();
            vm.Staff = DbContext.Users.Where(x => x.Roles.Any(y => y.Role.Name == Roles.Staff)).ToList();
            return View(vm);
        }

        public double[] timeOfday = new double[]
        {
            8,  8.5, 
            9,  9.5,
            10, 10.5, 
            11, 11.5, 
            12, 12.5,
            13, 13.5,
            14, 14.5,
            15, 15.5,
            16, 16.5,
            17, 17.5,
            18, 18.5,
            19, 19.5,
            20, 20.5,
            21, 21.5,
            22, 22.5,
            23, 23.5,
            0,  0.5,
            1,  1.5,
            2,  2.5,
            3,  3.5,
            4,  4.5,
            5,  5.5,
            6,  6.5,
            7,  7.5
        };

        public void CreateNightLogRows(NightLog nightLog)
        {
            if (nightLog.NightLogTimes == null)  nightLog.NightLogTimes = new List<NightLogTime>();
            foreach (var time in timeOfday)
            {
                if (nightLog.NightLogTimes.All(x => x.TimeStamp.TimeOfDay != TimeSpan.FromHours(time)))
                {
                    nightLog.NightLogTimes.Add(new NightLogTime
                    {
                        TimeStamp = DateTime.Now.Date.AddHours(time),
                        Comments = "",
                        SleepStatus = ""
                    });
                }
            }
        }

        [HttpPost]
        public ActionResult AddNightLog(NightLog_VM vm)
        {
            DbContext.NightLogs.AddOrUpdate(vm.NightLog);
            DbContext.SaveChanges();
            return RedirectToAction(nameof(AddNightLog));
        }

        [HttpPost]
        public ActionResult DeleteNightLog(int NightLogId)
        {
            try
            {
                var NightLog = DbContext.NightLogs.First(x => x.Id == NightLogId);
                DbContext.NightLogs.Remove(NightLog);
                DbContext.SaveChanges();
                return Json(true);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }
    }
}

AVStaffing/Controllers/PrintController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using AVStaffing.Models.Entities;

namespace AVStaffing.Controllers
{

    public class MedicalRecordPrintModel
    {
        public List<MedicineEntry> MedicinceEntries { get; set; }
        public MedicalRecord MedicalRecord { get; set; }
    }

    public class MedicineEntry
    {
        public Medication Medicine { get; set; }
        public List<MedicineCell> AdministeredMedicineRecord { get; set; }
    }

    public class MedicineCell 
    {
        public DateTime AdministeredDate { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime StopTime { get; set; }
        public string StaffInitials { get; set; }
    
    }


    public class  TreatmentPlanPrintModel
    {
        public TreatmentPlan TreatmentPlan { get; set; }
    }

    public class PrintController : BaseController
    {
        [HttpGet]
        public ActionResult BlankISP()
        {
            return View();
        }
        [HttpGet]
        public ActionResult ClinicalSummary(int id)
        {
            var clinicalSummary = DbContext.ClinicalSummaries
                .Include(x => x.Patient)
                .Include(x => x.Staff)
                .Include(x => x.Medicines.Select(y => y.Medication))
                .FirstOrDefault(x => x.Id == id);

            return View(clinicalSummary);
        }

        [HttpGet]
        public ActionResult ClinicalSummarytwo()
        {
            return View();
        }

        [HttpGet]
        public ActionResult COFSDischargeSummary()
        {
            return View();
        }

        [HttpGet]
        public ActionResult COFSINCISP()
        {
            return View();
        }

        [HttpGet]
        public ActionResult COFSInternationalIncidentForm()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DischargeSummary()
        {
            return View();
        }

        [HttpGet]
        public ActionResult MarCofSinc(int id)
        {
            var dbMar = DbContext.Mar
                .Include(x => x.AdministeredMedications).Include(x => x.AdministeredMedications.Select(y=>y.Medication)).Include(x=>x.AdministeredMedications.Select(y=>y.Staff))
                .Include(x => x.NotAdministeredMedicines).Include(x => x.NotAdministeredMedicines.Select(y=>y.Medication))
                .Include(x => x.Patient)
                .Include(x => x.Doctor)
                .Include(x => x.Staff).Include(x => x.Staff.Select(y => y.Staff)).FirstOrDefault(x=>x.Id == id);

            var vm = new MedicalRecordPrintModel();
            var lst = new List<MedicineEntry>();


            foreach (var medicine in dbMar.AdministeredMedications) 
            {
                var m = lst.FirstOrDefault(x => x.Medicine.Id == medicine.MedicationId);
                var medCell = new MedicineCell
                {
                    AdministeredDate = medicine.StartTime,
                    StartTime = medicine.StartTime,
                    StopTime = medicine.EndTime,
                    StaffInitials = medicine.Staff.Initials
                };

                if (m == null)
                {
                    lst.Add(new MedicineEntry { AdministeredMedicineRecord = new List<MedicineCell> { medCell }, Medicine = medicine.Medication });
                }
                else 
                {
                    m.AdministeredMedicineRecord.Add(medCell);
                }
            }
            vm.MedicinceEntries = lst;
            vm.MedicalRecord = dbMar;
            return View(vm);
        }
        public ActionResult NightLog(int id)
        {
            var dbPlan = DbContext.NightLogs
                .Include(x => x.NightLogTimes.Select(y => y.Staff))
                .Include(x => x.Patient).FirstOrDefault(x => x.Id == id);
            return View(dbPlan);
        }


        [HttpGet]
        public ActionResult TreatmentPlan(int id)
        {
            var dbPlan = DbContext.TreatmentPlans
                .Include(x=>x.Patient)
                .Include(x=>x.Goals)
                .Include(x=>x.Staff)
                .FirstOrDefault(x => x.Id == id);
            var plan = new TreatmentPlanPrintModel
            {
                TreatmentPlan = dbPlan
            };
            return View(plan);
        }
        public ActionResult ContinuedStayForm()
        {
            return View();
        }
        public ActionResult BehaviorPlan()
        {
            return View();
        }
        public ActionResult BehaviorModification()
        {
            return View();
        }
        public ActionResult RiskAssessment()
        {
            return View();
        }
    }
}

AVStaffing/Views/NightLog/NightLogList.cshtml
@using System.Security.Policy
@model System.Collections.Generic.IEnumerable<AVStaffing.Models.Entities.NightLog>

@{
    ViewBag.Title = "Proxies";

    var editNightLogPermission = User.HasPermission("NightLog-AddNightLog");
    var deleteNightLogPermission = User.HasPermission("NightLog-DeleteNightLog");
}
<div class="subheader py-2 py-lg-6  subheader-transparent " id="kt_subheader">
    <div class=" container  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <div class="d-flex align-items-center flex-wrap mr-1">
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <h5 class="text-dark font-weight-bold my-1 mr-5">
                    Night Log Management
                </h5>
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="#/" class="text-muted">
                            Reports
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#/" class="text-muted">
                            Night Logs
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="d-flex flex-column-fluid">
    <div class="container">
        <div class="card card-custom">
            <div class="card-header">
                <div class="card-title">
                    <span class="card-icon"><i class="fa fa-user text-primary"></i></span>
                    <h3 class="card-label">Night Log List</h3>
                </div>
                <div class="card-toolbar">
                    @if (editNightLogPermission)
                    {
                        <a href="@Url.Action("AddNightLog", "NightLog")" class="btn btn-primary font-weight-bolder">
                            <i class="la la-plus"></i>
                            Create new NightLog
                        </a>
                    }
                </div>
            </div>
            <div class="card-body">
                <table  class="table table-separate table-head-custom collapsed dataTable">
                    <thead>
                        <tr>
                            <th>Patient Name</th>
                            <th>Date </th>
                            <th>Action</th>
                        </tr>
                    <thead>

                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@item.Patient.FirstName @item.Patient.LastName</td>
                                <td>@item.DateOfAdmission.ToString("yyyy MM dd")</td>
                           
                                <td>
                                    <a style="cursor: pointer !important" href="@Url.Action("NightLog", "Print", new {id = item.Id})" id=@item.Id>
                                        <i class="fas fa-print text-success"></i>
                                    </a>
                                    @if (editNightLogPermission)
                                    {
                                        <a style="cursor: pointer !important" href="@Url.Action("AddNightLog", "NightLog", new {id = item.Id})" id=@item.Id>
                                            <i class="fas fa-pencil-alt text-primary"></i>
                                        </a>
                                    }
                                    @if (deleteNightLogPermission)
                                    {
                                        <a style="cursor: pointer !important" href="#/" class="deleteNightLog" data-id="@item.Id">
                                            <i class="fas fa-trash text-danger"></i>
                                        </a>
                                    }
                                </td>
                            </tr>
                            }
                        </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
     

        $(".deleteNightLog").click(function() {
            var id = $(this).data("id");
            var row = $(this).parents("tr");
            bootbox.confirm("Are you sure you want to delete this user ?",
                function(r) {
                    if (r) {
                        $.post("@Url.Action("DeleteNightLog", "NightLog")",
                                {
                                    NightLogId: id
                                })
                            .done(function() {
                                $(row).remove();
                            })
                            .fail(function() {

                            });
                    }
                });
        });

    </script>
}